// Forms & Client
export const SIGNUP_REQUESTING = "SIGNUP_REQUESTING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNIN_REQUESTING = "SIGNIN_REQUESTING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGN_OUT = "SIGN_OUT";
// User
export const USER_REQUESTING = "USER_REQUESTING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const UNSET_USER = "UNSET_USER";
// Movies
export const MOVIES_REQUESTING = "MOVIES_REQUESTING";
export const MOVIES_SUCCESS = "MOVIES_SUCCESS";
export const MY_MOVIES_REQUESTING = "MY_MOVIES_REQUESTING";
export const MY_MOVIES_SUCCESS = "MY_MOVIES_SUCCESS";
export const MOVIE_SEARCH_REQUESTING = "MOVIE_SEARCH_REQUESTING";
export const MOVIE_SEARCH_SUCCESS = "MOVIE_SEARCH_SUCCESS";
export const MOVIE_CATEGORY_REQUESTING = "MOVIE_CATEGORY_REQUESTING";
export const MOVIE_CATEGORY_SUCCESS = "MOVIE_CATEGORY_SUCCESS";
export const MOVIES_ERROR = "MOVIES_ERROR";
export const MOVIE_POSTING = "MOVIE_POSTING";
export const MOVIE_SUCCESS = "MOVIE_SUCCESS";
export const UPDATE_GENRE = "UPDATE_GENRE";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
// Playlists
export const PLAYLISTS_REQUESTING = "PLAYLISTS_REQUESTING";
export const PLAYLISTS_SUCCESS = "PLAYLISTS_SUCCESS";
export const PLAYLIST_REQUESTING = "PLAYLIST_REQUESTING";
export const PLAYLIST_SUCCESS = "PLAYLIST_SUCCESS";
export const PLAYLIST_ADD_REQUESTING = "PLAYLIST_ADD_REQUESTING";
export const PLAYLIST_ADD_SUCCESS = "PLAYLIST_ADD_SUCCESS";
export const PLAYLIST_ADD_MOVIE_REQUESTING = "PLAYLIST_ADD_MOVIE_REQUESTING";
export const PLAYLIST_ADD_MOVIE_SUCCESS = "PLAYLIST_ADD_MOVIE_SUCCESS";
export const PLAYLIST_REMOVE_MOVIE_REQUESTING =
  "PLAYLIST_REMOVE_MOVIE_REQUESTING";
export const PLAYLIST_REMOVE_MOVIE_SUCCESS = "PLAYLIST_REMOVE_MOVIE_SUCCESS";
export const PLAYLIST_UPDATE_ACTIVE_REQUESTING =
  "PLAYLIST_UPDATE_ACTIVE_REQUESTING";
export const PLAYLIST_UPDATE_ACTIVE_SUCCESS = "PLAYLIST_UPDATE_ACTIVE_SUCCESS";
export const PLAYLIST_DELETE_REQUESTING = "PLAYLIST_DELETE_REQUESTING";
export const PLAYLIST_DELETE_SUCCESS = "PLAYLIST_DELETE_SUCCESS";
export const PLAYLIST_INITIALIZE = "PLAYLIST_INITIALIZE";
export const PLAYLISTS_ERROR = "PLAYLISTS_ERROR";
export const PLAYLISTS_REMOVE = "PLAYLISTS_REMOVE";
// Ratings
export const RATINGS_REQUESTING = "RATINGS_REQUESTING";
export const RATINGS_SUCCESS = "RATINGS_SUCCESS";
export const RATINGS_ERROR = "RATINGS_ERROR";
export const RATING_ADD = "RATING_ADD";
export const RATINGS_REMOVE = "RATINGS_REMOVE";
// Notifications
export const TOGGLE_DISPLAY = "TOGGLE_DISPLAY";
