//Forms & Client
export const SIGNUP_REQUESTING = "SIGNUP_REQUESTING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNIN_REQUESTING = "SIGNIN_REQUESTING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGN_OUT = "SIGN_OUT";
export const DISPLAY_TOGGLE = "DISPLAY_TOGGLE";
//User
export const USER_REQUESTING = "USER_REQUESTING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const UNSET_USER = "UNSET_USER";
//Movies
export const MOVIES_REQUESTING = "MOVIES_REQUESTING";
export const MOVIES_SUCCESS = "MOVIES_SUCCESS";
export const MOVIES_ERROR = "MOVIES_ERROR";
export const MOVIE_POSTING = "MOVIE_POSTING";
export const MOVIE_SUCCESS = "MOVIE_SUCCESS";
export const MOVIE_ERROR = "MOVIE_ERROR";
//Ratings
export const RATING_ADD = "RATING_ADD";
